extend type Mutation {

  """
  Some Mutation
  """
  someMutation: String! @custom(resolver: "someMutation")
}

extend type Query {

  """
  Some Query
  """
  someQuery: String! @custom(resolver: "someQuery")

}