-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS _auth."AuthFactor" (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    "userAuthenticationId" uuid NOT NULL REFERENCES _auth."UserAuthentication"(id),
    provider text NOT NULL,
    meta text NOT NULL,
    hash text NOT NULL,
    "communicationAddress" text,
    "proofedAt" timestamp without time zone,
    "deletedAt" timestamp without time zone,
    "createdAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC'::text, now())
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS "AuthFactor_pkey" ON _auth."AuthFactor"(id uuid_ops);
CREATE UNIQUE INDEX IF NOT EXISTS "AuthFactor_userAuthenticationId_provider_deletedAt_idx" ON _auth."AuthFactor"("userAuthenticationId" uuid_ops,provider text_ops,"deletedAt" timestamp_ops);
CREATE UNIQUE INDEX IF NOT EXISTS "AuthFactor_userAuthenticationId_provider_idx" ON _auth."AuthFactor"("userAuthenticationId" uuid_ops,provider text_ops) WHERE "deletedAt" IS NULL;
