#type File @table {
type PrivateFile @table(schemaName: "private", tableName: "File") {
  id: ID! @isUnique
  url: String
  container: String @isUnique(name: "FileSource")
  fileName: Int! @isUnique(name: "FileSource")
}
