type Post @table {#@migrate(oldName:"PostOld"){
  id: ID! @isUnique
  title: String
  content: String
  owner: User! @relation(name: "PostOwner", onDelete: "restrict", onUpdate: "cascade")
  ownerSecret: String
  titleImage: PrivateFile @relation(name: "TitleImage")
  contributors: [User!]! @relation(name: "PostContributors")
  contributorSecret: String
}