
type Post @table {
  id: ID! @isUnique
  _typenames: [POST_TYPES!]!
  title: String
  content: String
  owner: User! @relation(name: "PostOwner")
  ownerSecret: String
  titleImage: File @relation(name: "TitleImage")
  contributors: [User!]! @relation(name: "PostContributors")
  contributorSecret: String
}

directive @slugify on FIELD