#type UniqueDemo @table @versioning {
#  id: ID! @unique
#  updatedAt: String @updatedAt
#  createdAt: String @createdAt
#
#  simpleUnique: String @unique
#  namedUnique: String @unique(name: "namedUnique")
#
#  multipleUnique2: String @unique(name: "multipleUnique")
#  multipleUnique1: String @unique(name: "multipleUnique")


#  multipleUniqueExpression1: Boolean @unique(name: "multipleUniqueExpression")
#  multipleUniqueExpression2: Boolean @unique(name: "multipleUniqueExpression" condition: "(\"multipleUniqueExpression1\" = true) AND (\"multipleUniqueExpression2\" = true)")



#}
