#type User @table @check(notGenericAddress:"email != 'mail@fullstack.build' AND email != 'info@fullstack.build'"){
type User @table @check(notGenericAddress:"(((email)::text <> 'mail@fullstack.build'::text) AND ((email)::text <> 'info@fullstack.build'::text))"){
  id: ID! @isUnique
  email: String @isUnique @default(value: "test@test.de") @validate(isEmail:null, contains: "fullstack.build")
  gender: Gender!
  username: String
  firstLetterOfUserName: String @computed(expression: "FirstNOfField", params: {n: 1, field: "username"})
  payload: JSON @migrate(oldName: "payloadOld")
  posts: [Post!]! @relation(name: "PostOwner")
  postContributions: [Post!]! @relation(name: "PostContributors")
  stripeAccount: String @custom(resolver: "stripeAccount")
  testDefault: String @type(name: "Date") @default(expression: "now()")

  #type: UserType
  #privatePayload: PrivatePayload @subtype(fieldName: "type", value: "private")
  #businessPayload: BusinessPayload @subtype(fieldName: "type", value: "business")
}

#type Adress {
#  city: String
#  street: String
#  fullname: String
#}

#type Location {
#  lgt: Int
#  long: Int
#}

#type Personal {
#  size: Int
#  location: Location
#}

#type UserPayload {
#  address: Address
#  personal: Personal
#}

#type PrivatePayload {
#  brithday: String
#  address: String
#}

#type BusinessPayload {
#  company: String
#  address: String
#}

type AdditionPayload {
  sum: Int!
}

extend type Query {
  add(a: Int! b: Int!): AdditionPayload @custom(resolver: "add")
}

enum UserType {
  private
  business
}

enum Gender {
  male
  female
}


