type User @table {
  id: ID! @isUnique
  email: String @isUnique
  username: String
  firstLetterOfUserName: String @computed(expression: "FirstNOfField", params: {n: 1})
  payload: String
  posts: [Post!]! @relation(name: "PostOwner")
  postContributions: [Post!]! @relation(name: "PostContributors")
}