extend type Mutation {

  """
  Some Mutation
  """
  someMutation: String! @custom(resolver: "someMutation")
}

extend type Query {

  """
  Some Query
  """
  someQuery: String! @custom(resolver: "someQuery")

}

extend type Mutation {
  """
  Creates a new file for upload. Login required.
  """
  createFileSystem(extension: String!, type: FILE_TYPES): UploadFile @custom(resolver: "createFileSystem")

  """
  Verifies a new file after upload. Login required.
  """
  verifyFileSystem(fileName: String!): BucketFile @custom(resolver: "verifyFileSystem")
}