-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS _meta."Auth" (
    key character varying PRIMARY KEY,
    value character varying
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS "Auth_pkey" ON _meta."Auth"(key text_ops);
