-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS _meta."AuthFactor" (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    "userAuthenticationId" uuid NOT NULL REFERENCES _meta."UserAuthentication"(id),
    provider text NOT NULL,
    meta text NOT NULL,
    hash text NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT timezone('UTC'::text, now())
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS "AuthFactor_pkey" ON _meta."AuthFactor"(id uuid_ops);
CREATE UNIQUE INDEX IF NOT EXISTS "AuthFactor_userAuthenticationId_provider_idx" ON _meta."AuthFactor"("userAuthenticationId" uuid_ops,provider text_ops);
