type Post @table @migrate(from:"PostOld"){
  id: ID! @unique
  title: String
  content: String
  images: [String]
  owner: User! @relation(name: "PostOwner", onDelete: "restrict", onUpdate: "restrict")
  ownerSecret: String
  titleImage: PrivateFile @relation(name: "TitleImage")
  contributors: [User!]! @relation(name: "PostContributors")
  contributorSecret: String
}
